$(document).ready(function(){
    $(".movie_content").ready(()=>{
        console.log('ready')
        $(".movie_content").each((index,movie)=>{
            movie.click(()=>{
                console.log("點擊")
            })
        })
    })
})